---
# Rollback-specific configuration

# Allowed versions for transition cycle
allowed_versions:
  - "10.2.4"
  - "11.0.2"

# Default direction
current_version: "10.2.4"
target_version: "11.0.2"

# Rollback wait timeout in seconds
rollback_reboot_timeout: 900
